include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_type_to_string
    - empty_statements
    - hash_and_equals
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - prefer_generic_function_type_aliases
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - unnecessary_statements

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"