name: cognitive_training
description: Когинитивные тренировки
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.4+00204

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^5.0.0-beta.52
  nsg_data:
    path: ../nsg_data
  nsg_controls:
    path: ../nsg_controls
  nsg_login:
    path: ../nsg_login

  intl: any
  flutter_svg: ^2.0.10+1
  simple_shadow: ^0.3.0
  flutter_slidable: ^4.0.0
  slidable_button: ^1.3.1
  flutter_fadein: ^2.0.0
  jiffy: ^6.0.0
  flutter_circle_color_picker: ^0.3.0
  soundpool: ^2.4.1
  flutter_localizations:
    sdk: flutter
  flex_color_picker: ^3.3.0
  wakelock_plus: ^1.1.1
  icons_launcher: ^2.1.7
  video_player_win: ^2.3.11
  video_player_macos: ^2.0.1
  video_player: ^2.9.1
  network_info_plus: ^4.1.0+1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/svg/
    - lib/assets/audios/
    - lib/assets/images/
